# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Unity-iPhone
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'BatchedBridge',
    'RCTImage',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  #native call js
  pod 'react-native-eval',:path => '../node_modules/react-native-eval'
  
  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end



end
